apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: frontend-angular 
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: frontend-angular 
 template: 
   metadata: 
    labels: 
     app: frontend-angular
     env: prod 
   spec: 
    containers: 
    - name: frontend-angular 
      image: ichrakmhiri1506/frontend:latest
      ports:
      - containerPort: 4300
      command: ["ng","serve","--host","0.0.0.0","--port","4300"]
      env:
      - name: URL
        value: "http://10.0.0.10:32221"